version: '2.1'
services:

  master: 
    build:
      context: jenkins-master
    container_name: jenkins-master
    restart: always
    ports:
      - "50000:50000"
      - "2375:2375"
    volumes:
      - "/var/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/usr/bin/docker-compose:/usr/bin/docker-compose"
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/share/composer:/usr/share/composer"
      - "/usr/share/platform:/usr/share/platform"
    env_file:
      - ./jenkins-master/jenkins.env
      - ./jenkins-master/java.env
    working_dir: /var/jenkins_home
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 3
      test: ["CMD", "curl", "-f", "http://localhost:8080/securityRealm/finishLogin"]

  nginx:
    build:
      context: jenkins-nginx
    container_name: jenkins-nginx
    ports:
      - "80:80"
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 3
      test: ["CMD", "curl", "-f", "http://localhost/securityRealm/finishLogin"]
    command: nginx
    links:
      - master:jenkins-master

  composer:
    build:
      context: jenkins-composer
    container_name: jenkins-composer
    volumes:
      - "/var/cache/composer:/var/cache/composer"
      - "/usr/share/composer:/usr/share/composer"
    environment:
      - COMPOSER_CACHE_DIR=/var/cache/composer
    working_dir: /var/jenkins_home
