version: '2'
services:
  master: 
    build:
      context: jenkins-master
    container_name: jenkins-master
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
      - "2375:2375"
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/usr/bin/docker-compose:/usr/bin/docker-compose"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./jenkins-master/jenkins.env
      - ./jenkins-master/java.env
    entrypoint:
      - /usr/local/bin/jenkins.sh
    depends_on:
      - composer
    working_dir: /var/jenkins_home
  composer:
    container_name: composer
    restart: "no"
    image: composer/composer:1.2-php5-alpine
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "composer-cache:/var/cache/composer"
    environment:
      - COMPOSER_CACHE_DIR=/var/cache/composer
    working_dir: /var/jenkins_home
volumes:
  jenkins-data:
    driver: local-persist
    driver_opts:
      mountpoint: /var/jenkins_home
  composer-cache:
    driver: local-persist
    driver_opts:
      mountpoint: /var/cache/composer
